In [33]:
import pandas as pd

df = pd.read_csv(r"D:\Review 4\datasets\QS_World_University_Rankings_2025_Top_global_universities.csv", encoding='cp1252')

In [34]:
df.head()

,RANK_2025,RANK_2024,Institution_Name,Location,Region,SIZE,FOCUS,RES.,STATUS,Academic_Reputation_Score,...,International_Faculty_Rank,International_Students_Score,International_Students_Rank,International_Research_Network_Score,International_Research_Network_Rank,Employment_Outcomes_Score,Employment_Outcomes_Rank,Sustainability_Score,Sustainability_Rank,Overall_Score
0,1,1,Massachusetts Institute of Technology (MIT),United States,Americas,M,CO,VH,B,100.0,...,100,86.8,143,96.0,58,100.0,8,99.0,15=,100
1,2,6,Imperial College London,United Kingdom,Europe,L,FC,VH,A,98.5,...,66,99.6,44,97.4,34,93.4,61,99.7,6,98.5
2,3,3,University of Oxford,United Kingdom,Europe,L,FC,VH,A,100.0,...,120,97.7,73,100.0,1,100.0,3,85.0,126,96.9
3,4,4,Harvard University,United States,Americas,L,FC,VH,B,100.0,...,269,69.0,215,99.6,5,100.0,1,84.4,130,96.8
4,5,2,University of Cambridge,United Kingdom,Europe,L,FC,VH,A,100.0,...,73,94.8,98,99.3,10,100.0,5,84.8,127=,96.7

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503 entries, 0 to 1502
Data columns (total 28 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   RANK_2025                             1503 non-null   object
 1   RANK_2024                             1482 non-null   object
 2   Institution_Name                      1503 non-null   object
 3   Location                              1503 non-null   object
 4   Region                                1503 non-null   object
 5   SIZE                                  1503 non-null   object
 6   FOCUS                                 1503 non-null   object
 7   RES.                                  1503 non-null   object
 8   STATUS                                1466 non-null   object
 9   Academic_Reputation_Score             1503 non-null   float64
 10  Academic_Reputation_Rank              1503 non-null   object
 11  Employer_Reputation_Score             1503 non-null   float64
 12  Employer_Reputation_Rank              1503 non-null   object
 13  Faculty_Student_Score                 1503 non-null   float64
 14  Faculty_Student_Rank                  1503 non-null   object
 15  Citations_per_Faculty_Score           1503 non-null   float64
 16  Citations_per_Faculty_Rank            1503 non-null   object
 17  International_Faculty_Score           1403 non-null   float64
 18  International_Faculty_Rank            1403 non-null   object
 19  International_Students_Score          1445 non-null   float64
 20  International_Students_Rank           1445 non-null   object
 21  International_Research_Network_Score  1502 non-null   float64
 22  International_Research_Network_Rank   1502 non-null   object
 23  Employment_Outcomes_Score             1503 non-null   float64
 24  Employment_Outcomes_Rank              1503 non-null   object
 25  Sustainability_Score                  1484 non-null   float64
 26  Sustainability_Rank                   1484 non-null   object
 27  Overall_Score                         601 non-null    object
dtypes: float64(9), object(19)
memory usage: 328.9+ KB

In [36]:
df.describe()

,Academic_Reputation_Score,Employer_Reputation_Score,Faculty_Student_Score,Citations_per_Faculty_Score,International_Faculty_Score,International_Students_Score,International_Research_Network_Score,Employment_Outcomes_Score,Sustainability_Score
count,1503.000000,1503.000000,1503.000000,1503.000000,1403.000000,1445.000000,1502.000000,1503.000000,1484.000000
mean,20.286693,19.787292,28.128676,23.503460,30.736707,25.580346,50.129095,23.825083,24.309299
std,22.326168,23.784738,27.613017,27.870692,34.344365,31.098689,29.866588,27.351315,31.074718
min,1.300000,1.100000,1.000000,1.000000,1.000000,1.000000,1.000000,1.200000,1.000000
25%,6.300000,4.300000,7.300000,2.800000,4.200000,2.900000,22.725000,4.000000,1.300000
50%,11.000000,9.400000,16.000000,9.900000,12.500000,9.600000,51.100000,11.800000,6.750000
75%,23.500000,25.300000,40.400000,36.400000,51.600000,38.300000,77.100000,33.400000,39.500000
max,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [37]:
len(df.columns)

28

In [38]:
df.isna().sum()

RANK_2025                                 0
RANK_2024                                21
Institution_Name                          0
Location                                  0
Region                                    0
SIZE                                      0
FOCUS                                     0
RES.                                      0
STATUS                                   37
Academic_Reputation_Score                 0
Academic_Reputation_Rank                  0
Employer_Reputation_Score                 0
Employer_Reputation_Rank                  0
Faculty_Student_Score                     0
Faculty_Student_Rank                      0
Citations_per_Faculty_Score               0
Citations_per_Faculty_Rank                0
International_Faculty_Score             100
International_Faculty_Rank              100
International_Students_Score             58
International_Students_Rank              58
International_Research_Network_Score      1
International_Research_Network_Rank       1
Employment_Outcomes_Score                 0
Employment_Outcomes_Rank                  0
Sustainability_Score                     19
Sustainability_Rank                      19
Overall_Score                           902
dtype: int64

In [39]:
df["RANK_2024"].unique()

array(['1', '6', '3', '4', '2', '5', '7', '8', '9', '15', '12', '10',
       '14', '17', '26', '13', '19', '25', '11', '16', '24', '21', '36',
       '22', '37', '30', '34', '41', '28', '23', '32', '47', '42', '50',
       '40', '43', '29', '38', '33', '51', '60', '44', '46', '45', '56',
       '55', '53', '76', '65', '52', '54', '57', '70', '61', '59', '68',
       '58', '79', '69', '67', '64', '95', '62', '71', '73', '85', '63',
       '72', '84', '81', '89', '75', '87', '91', '80', '90', '78', '83',
       '99', '103', '93', '111', '98', '100', '106', '107', '180', '119',
       '105', '104', '113', '121', '123', '109', '97', '112', '102',
       '115', '149', '117', '145', '114', '173', '140', '116', '120',
       '171', '118', '110', '124', '134', '154', '130', '137', '159',
       '129', '122', '126', '143', '141', '158', '197', '148', '136',
       '176', '128', '132', '151', '139', '164', '230', '162', '153',
       '169', '196', '183', '189', '163', '198', '188', '199', '310',
       '167', '184', '214', '203', '205', '216', '209', '187', '194',
       '166', '233', '182', '179', '364', '195', '192', '202', '237',
       '215', '225', '206', '228', '168', '242', '217', '226', '207',
       '213', '271', '229', '212', '220', '285', '239', '211', '256',
       '210', '246', '250', '219', '208', '224', '263', '252', '241',
       '254', '248', '218', '261', '280', '284', '295', '232', '243',
       '281', '235', '262', '255', '266', '551', '278', '292', '300',
       '264', '307', '272', '222', '289', '298', '245', '253', '259',
       '251', '276', '328', '301', '336', '319', '268', '244', '291',
       '283', '260', '275', '297', '340', '236', '371', '345', '302',
       '362', '274', '304', '306', '312', '315', '342', '360', '318',
       '355', '347', '349', '326', '404', '332', '299', '407', '323',
       '580', '294', '369', '380', '351', '343', '334', '379', '313',
       '335', '322', '367', '381', '358', '344', '454', '392', '353',
       '384', '382', '498', '354', '1401+', '427', '375', '387', '400',
       '595', '368', '444', '489', '436', '421', '410', '396', '431',
       '481', '374', '399', '415', '413', '441', '514', '426', '446',
       '440', '452', '418', '403', '428', '451', '476', '473', '429',
       '469', '409', '505', '485', '491', '494', '486', '465', '478',
       '621-630', '419', '459', '472', '460', '502', '534', nan, '386',
       '561', '590', '461', '544', '511', '464', '567', '530', '563',
       '529', '556', '520', '526', '523', '701-710', '611-620', '480',
       '479', '509', '571', '641-650', '540', '548', '582', '586',
       '1201-1400', '290', '731-740', '538', '691-700', '542', '601-610',
       '525', '600', '577', '741-750', '671-680', '651-660', '631-640',
       '545', '771-780', '555', '721-730', '661-670', '761-770',
       '681-690', '575', '711-720', '751-760', '801-850', '781-790',
       '593', '791-800', '851-900', '951-1000', '901-950', '1001-1200'],
      dtype=object)

In [40]:
df["STATUS"].unique()

array(['B', 'A', 'C', nan], dtype=object)

In [41]:
df2 = df.dropna(subset=["RANK_2024"])

In [42]:
df.head()

,RANK_2025,RANK_2024,Institution_Name,Location,Region,SIZE,FOCUS,RES.,STATUS,Academic_Reputation_Score,...,International_Faculty_Rank,International_Students_Score,International_Students_Rank,International_Research_Network_Score,International_Research_Network_Rank,Employment_Outcomes_Score,Employment_Outcomes_Rank,Sustainability_Score,Sustainability_Rank,Overall_Score
0,1,1,Massachusetts Institute of Technology (MIT),United States,Americas,M,CO,VH,B,100.0,...,100,86.8,143,96.0,58,100.0,8,99.0,15=,100
1,2,6,Imperial College London,United Kingdom,Europe,L,FC,VH,A,98.5,...,66,99.6,44,97.4,34,93.4,61,99.7,6,98.5
2,3,3,University of Oxford,United Kingdom,Europe,L,FC,VH,A,100.0,...,120,97.7,73,100.0,1,100.0,3,85.0,126,96.9
3,4,4,Harvard University,United States,Americas,L,FC,VH,B,100.0,...,269,69.0,215,99.6,5,100.0,1,84.4,130,96.8
4,5,2,University of Cambridge,United Kingdom,Europe,L,FC,VH,A,100.0,...,73,94.8,98,99.3,10,100.0,5,84.8,127=,96.7

In [13]:
df2.isna().sum()

RANK_2025                                 0
RANK_2024                                 0
Institution_Name                          0
Location                                  0
Region                                    0
SIZE                                      0
FOCUS                                     0
RES.                                      0
STATUS                                   36
Academic_Reputation_Score                 0
Academic_Reputation_Rank                  0
Employer_Reputation_Score                 0
Employer_Reputation_Rank                  0
Faculty_Student_Score                     0
Faculty_Student_Rank                      0
Citations_per_Faculty_Score               0
Citations_per_Faculty_Rank                0
International_Faculty_Score              97
International_Faculty_Rank               97
International_Students_Score             57
International_Students_Rank              57
International_Research_Network_Score      1
International_Research_Network_Rank       1
Employment_Outcomes_Score                 0
Employment_Outcomes_Rank                  0
Sustainability_Score                     16
Sustainability_Rank                      16
Overall_Score                           885
dtype: int64

In [14]:
df2.dropna(subset=["STATUS"],inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_35064\2366940183.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.dropna(subset=["STATUS"],inplace=True)

In [15]:
df2.isna().sum()

RANK_2025                                 0
RANK_2024                                 0
Institution_Name                          0
Location                                  0
Region                                    0
SIZE                                      0
FOCUS                                     0
RES.                                      0
STATUS                                    0
Academic_Reputation_Score                 0
Academic_Reputation_Rank                  0
Employer_Reputation_Score                 0
Employer_Reputation_Rank                  0
Faculty_Student_Score                     0
Faculty_Student_Rank                      0
Citations_per_Faculty_Score               0
Citations_per_Faculty_Rank                0
International_Faculty_Score              79
International_Faculty_Rank               79
International_Students_Score             39
International_Students_Rank              39
International_Research_Network_Score      1
International_Research_Network_Rank       1
Employment_Outcomes_Score                 0
Employment_Outcomes_Rank                  0
Sustainability_Score                     16
Sustainability_Rank                      16
Overall_Score                           853
dtype: int64

In [16]:
cols= df2.columns
cols_missing = [
    "International_Faculty_Rank",
    "International_Students_Rank",
    "Sustainability_Rank",
    "International_Research_Network_Rank",
    "International_Research_Network_Score",
    "Overall_Score",
    "Sustainability_Score",
    "International_Students_Score",
    "International_Faculty_Score"

]
rank_cols=[
    "International_Faculty_Rank",
    "International_Students_Rank",
    "Sustainability_Rank",
    "International_Research_Network_Rank",
    "Academic_Reputation_Rank",
    "Employment_Outcomes_Rank",
    "Sustainability_Rank",
    "Employer_Reputation_Rank",
    "Faculty_Student_Rank",
    "Citations_per_Faculty_Rank"
]

In [17]:
for col in rank_cols:
    df2[col] = df2[col].str.replace("+", "")
    df2[col] = df2[col].str.replace("=", "")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_35064\4086603414.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = df2[col].str.replace("+", "")
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_35064\4086603414.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = df2[col].str.replace("=", "")

In [18]:
for col in cols_missing:
    df2[col] = pd.to_numeric(df2[col], errors="coerce")
    df2[col] = df2[col].fillna(round(df2[col].mean(),1))

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_35064\479788578.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = pd.to_numeric(df2[col], errors="coerce")
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_35064\479788578.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = df2[col].fillna(round(df2[col].mean(),1))

In [19]:
df2.isna().sum()

RANK_2025                               0
RANK_2024                               0
Institution_Name                        0
Location                                0
Region                                  0
SIZE                                    0
FOCUS                                   0
RES.                                    0
STATUS                                  0
Academic_Reputation_Score               0
Academic_Reputation_Rank                0
Employer_Reputation_Score               0
Employer_Reputation_Rank                0
Faculty_Student_Score                   0
Faculty_Student_Rank                    0
Citations_per_Faculty_Score             0
Citations_per_Faculty_Rank              0
International_Faculty_Score             0
International_Faculty_Rank              0
International_Students_Score            0
International_Students_Rank             0
International_Research_Network_Score    0
International_Research_Network_Rank     0
Employment_Outcomes_Score               0
Employment_Outcomes_Rank                0
Sustainability_Score                    0
Sustainability_Rank                     0
Overall_Score                           0
dtype: int64

In [20]:
df2.columns
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1446 entries, 0 to 1501
Data columns (total 28 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   RANK_2025                             1446 non-null   object
 1   RANK_2024                             1446 non-null   object
 2   Institution_Name                      1446 non-null   object
 3   Location                              1446 non-null   object
 4   Region                                1446 non-null   object
 5   SIZE                                  1446 non-null   object
 6   FOCUS                                 1446 non-null   object
 7   RES.                                  1446 non-null   object
 8   STATUS                                1446 non-null   object
 9   Academic_Reputation_Score             1446 non-null   float64
 10  Academic_Reputation_Rank              1446 non-null   object
 11  Employer_Reputation_Score             1446 non-null   float64
 12  Employer_Reputation_Rank              1446 non-null   object
 13  Faculty_Student_Score                 1446 non-null   float64
 14  Faculty_Student_Rank                  1446 non-null   object
 15  Citations_per_Faculty_Score           1446 non-null   float64
 16  Citations_per_Faculty_Rank            1446 non-null   object
 17  International_Faculty_Score           1446 non-null   float64
 18  International_Faculty_Rank            1446 non-null   float64
 19  International_Students_Score          1446 non-null   float64
 20  International_Students_Rank           1446 non-null   float64
 21  International_Research_Network_Score  1446 non-null   float64
 22  International_Research_Network_Rank   1446 non-null   float64
 23  Employment_Outcomes_Score             1446 non-null   float64
 24  Employment_Outcomes_Rank              1446 non-null   object
 25  Sustainability_Score                  1446 non-null   float64
 26  Sustainability_Rank                   1446 non-null   float64
 27  Overall_Score                         1446 non-null   float64
dtypes: float64(14), object(14)
memory usage: 327.6+ KB

In [21]:
def clean_range(value):
    
    value = str(value)
    value = value.replace("=", "").replace("+", "")
    if "-" in value:
        
        start= value.split("-")[0]
        end=value.split("-")[1]

        
        return (float(start) + float(end)) / 2
    
    return pd.to_numeric(value, errors="coerce")


rank_cols = [
    "RANK_2024",
    "RANK_2025"
]

for col in rank_cols:
    df2[col] = df2[col].apply(clean_range)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_35064\3589652877.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = df2[col].apply(clean_range)

In [22]:
df2.tail(10)

,RANK_2025,RANK_2024,Institution_Name,Location,Region,SIZE,FOCUS,RES.,STATUS,Academic_Reputation_Score,...,International_Faculty_Rank,International_Students_Score,International_Students_Rank,International_Research_Network_Score,International_Research_Network_Rank,Employment_Outcomes_Score,Employment_Outcomes_Rank,Sustainability_Score,Sustainability_Rank,Overall_Score
1491,1401.0,1401.0,Universitas Kristen Petra,Indonesia,Asia,M,FO,HI,C,7.1,...,701.0,1.1,701.0,6.0,701.0,2.5,701,1.0,701.0,42.1
1492,1401.0,1401.0,Universitas Muhammadiyah Surakarta,Indonesia,Asia,L,FO,HI,B,5.5,...,701.0,1.1,701.0,4.5,701.0,2.3,701,1.0,701.0,42.1
1493,1401.0,1300.5,Universiti Sains Islam Malaysia,Malaysia,Asia,M,CO,HI,A,6.6,...,701.0,6.1,701.0,12.5,701.0,3.3,701,1.0,701.0,42.1
1494,1401.0,1300.5,University of Central Oklahoma,United States,Americas,L,CO,MD,A,5.6,...,654.0,9.9,701.0,5.2,701.0,2.9,701,1.0,701.0,42.1
1495,1401.0,1401.0,University of Craiova,Romania,Europe,L,CO,HI,A,4.5,...,530.4,25.7,531.9,21.8,701.0,13.4,701,1.0,701.0,42.1
1497,1401.0,1401.0,University of Mataram,Indonesia,Asia,XL,FO,MD,A,6.4,...,701.0,1.0,701.0,3.7,701.0,2.2,701,1.0,701.0,42.1
1498,1401.0,1300.5,University of Montana Missoula,United States,Americas,M,CO,HI,A,3.0,...,701.0,1.9,701.0,6.5,701.0,3.1,701,1.0,701.0,42.1
1499,1401.0,1401.0,University of Oradea,Romania,Europe,L,FC,MD,A,5.6,...,701.0,5.2,701.0,34.5,701.0,6.2,701,2.3,701.0,42.1
1500,1401.0,1300.5,University of San Carlos,Philippines,Asia,M,CO,MD,C,7.2,...,701.0,2.1,701.0,6.4,701.0,9.6,701,1.0,701.0,42.1
1501,1401.0,1401.0,"University Politehnica of Timisoara, UPT",Romania,Europe,L,FO,VH,A,4.1,...,701.0,2.5,701.0,18.6,701.0,3.9,701,1.1,701.0,42.1

In [23]:
df2["Location"].value_counts()

Location
United States             193
United Kingdom             90
China (Mainland)           71
Japan                      48
Russia                     47
                         ...
Sudan                       1
Syrian Arab Republic        1
Bosnia and Herzegovina      1
Guatemala                   1
Honduras                    1
Name: count, Length: 100, dtype: int64

In [24]:
df2["Institution_Name"].duplicated().sum()

np.int64(0)

Tasks

In [25]:
#TASKS 

# Analyze ranking distribution by country.

country_distribution = df2["Location"].value_counts()

print(country_distribution.head(10))

Location
United States       193
United Kingdom       90
China (Mainland)     71
Japan                48
Russia               47
Germany              46
India                43
South Korea          43
Italy                42
Australia            38
Name: count, dtype: int64

In [26]:
#Identify:
#Top universities by region
#Countries dominating global education
#Score trends

top_universities_region = df2.sort_values("RANK_2025").groupby("Region").head(10)

print(top_universities_region[["Institution_Name", "Region", "RANK_2025"]])

                                      Institution_Name    Region  RANK_2025
0         Massachusetts Institute of Technology (MIT)   Americas        1.0
1                              Imperial College London    Europe        2.0
2                                 University of Oxford    Europe        3.0
3                                   Harvard University  Americas        4.0
4                              University of Cambridge    Europe        5.0
5                                  Stanford University  Americas        6.0
6    ETH Zurich - Swiss Federal Institute of Techno...    Europe        7.0
7               National University of Singapore (NUS)      Asia        8.0
8                                                  UCL    Europe        9.0
9         California Institute of Technology (Caltech)  Americas       10.0
10                          University of Pennsylvania  Americas       11.0
11            University of California, Berkeley (UCB)  Americas       12.0
12                         The University of Melbourne   Oceania       13.0
13                                   Peking University      Asia       14.0
14   Nanyang Technological University, Singapore (NTU)      Asia       15.0
15                                  Cornell University  Americas       16.0
16                         The University of Hong Kong      Asia       17.0
17                            The University of Sydney   Oceania       18.0
18     The University of New South Wales (UNSW Sydney)   Oceania       19.0
19                                 Tsinghua University      Asia       20.0
20                               University of Chicago  Americas       21.0
21                                Princeton University  Americas       22.0
22                                     Yale University  Americas       23.0
23                                      Université PSL    Europe       24.0
25                                                EPFL    Europe       26.0
26                         The University of Edinburgh    Europe       27.0
27                      Technical University of Munich    Europe       28.0
29                  The Australian National University   Oceania       30.0
30                           Seoul National University      Asia       31.0
32                             The University of Tokyo      Asia       32.0
34                        The University of Manchester    Europe       34.0
35          The Chinese University of Hong Kong (CUHK)      Asia       36.0
36                                   Monash University   Oceania       37.0
38                                    Fudan University      Asia       39.0
40                        The University of Queensland   Oceania       40.0
44                       Shanghai Jiao Tong University      Asia       45.0
64                          The University of Auckland   Oceania       65.0
76                 The University of Western Australia   Oceania       77.0
81                          The University of Adelaide   Oceania       82.0
87                     University of Technology Sydney   Oceania       88.0
170                            University of Cape Town    Africa      171.0
267                        University of Witwatersrand    Africa      267.0
295                            Stellenbosch University    Africa      296.0
312                         University of Johannesburg    Africa      312.0
349                                   Cairo University    Africa      350.0
353                             University of Pretoria    Africa      354.0
410                   The American University in Cairo    Africa      410.0
590                        University of Kwazulu-Natal    Africa      587.0
591                              Ain Shams University     Africa      592.0
777                       Université de Tunis El Manar    Africa      775.5

In [27]:
#Countries dominating global education

dominant_countries = df2["Location"].value_counts()

print(dominant_countries.head(10))

Location
United States       193
United Kingdom       90
China (Mainland)     71
Japan                48
Russia               47
Germany              46
India                43
South Korea          43
Italy                42
Australia            38
Name: count, dtype: int64

In [28]:
#Score trends

print(df2["Overall_Score"].describe())

count    1446.000000
mean       42.082089
std        12.059374
min        20.800000
25%        42.100000
50%        42.100000
75%        42.100000
max       100.000000
Name: Overall_Score, dtype: float64

In [29]:
df2.describe()

,RANK_2025,RANK_2024,Academic_Reputation_Score,Employer_Reputation_Score,Faculty_Student_Score,Citations_per_Faculty_Score,International_Faculty_Score,International_Faculty_Rank,International_Students_Score,International_Students_Rank,International_Research_Network_Score,International_Research_Network_Rank,Employment_Outcomes_Score,Sustainability_Score,Sustainability_Rank,Overall_Score
count,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000
mean,736.272822,727.999308,20.788728,20.226763,28.223582,23.927593,30.624620,530.447165,25.732849,531.856224,50.778008,532.990318,24.147718,25.072683,529.694467,42.082089
std,427.196538,420.267103,22.597296,24.009172,27.525859,27.995096,33.225221,217.387678,30.606796,220.631956,29.865286,224.897728,27.478844,31.179648,224.239950,12.059374
min,1.000000,1.000000,1.300000,1.100000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.200000,1.000000,1.000000,20.800000
25%,362.000000,360.500000,6.400000,4.400000,7.500000,2.800000,4.600000,381.250000,3.025000,372.250000,23.625000,364.250000,4.100000,1.400000,363.000000,42.100000
50%,725.500000,725.500000,11.500000,9.800000,16.200000,10.500000,14.400000,674.500000,10.800000,701.000000,51.900000,701.000000,12.200000,7.900000,701.000000,42.100000
75%,1100.500000,1100.500000,24.000000,26.175000,40.850000,37.675000,46.900000,701.000000,37.775000,701.000000,77.775000,701.000000,33.875000,40.400000,701.000000,42.100000
max,1401.000000,1401.000000,100.000000,100.000000,100.000000,100.000000,100.000000,701.000000,100.000000,701.000000,100.000000,701.000000,100.000000,100.000000,701.000000,100.000000

In [30]:
#Compare rankings and academic reputation scores.

print(df[["RANK_2025","Academic_Reputation_Score"]].head())

corr = df[["RANK_2025","Academic_Reputation_Score"]].head().corr()
print(corr)

  RANK_2025  Academic_Reputation_Score
0         1                      100.0
1         2                       98.5
2         3                      100.0
3         4                      100.0
4         5                      100.0
                           RANK_2025  Academic_Reputation_Score
RANK_2025                   1.000000                   0.353553
Academic_Reputation_Score   0.353553                   1.000000

In [31]:
#Find countries with the highest average university scores.

highest_avg_scores = df2.groupby("Location")["Overall_Score"].mean().sort_values(ascending=False)


print(highest_avg_scores.head(10))

Location
Singapore         67.766667
Hong Kong SAR     67.314286
Switzerland       54.277778
Qatar             52.000000
Netherlands       51.730769
Sweden            50.987500
Denmark           48.200000
Australia         47.397368
United Kingdom    45.886667
Canada            45.444828
Name: Overall_Score, dtype: float64

In [32]:
#Build ranking-based insights for students.

##Universities with high academic reputation scores often provide better research opportunities.
##Students aiming for globally recognized education should target universities in the USA, UK, and Europe.